#!/usr/bin/env python3

# Copyright (c) 2025 Pavel Vondřička <pavel.vondricka@ff.cuni.cz>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# dated June, 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import sys
import http
import requests


NAMETAG_API_URL = "http://lindat.mff.cuni.cz/services/nametag/api/recognize"
DEFAULT_MODEL = 'en'

def nametag_lindat(model, text, informat, outformat, url):
    """
    Send a text to NameTag web service and return the results
    """
    params = {
        "model": model,
        "data": text,
        "input": informat,
        "output": outformat
    }
    response = requests.post(url, params)
    if not response.ok:
        error_type = (
            "NAMETAG NOT AVAILABLE: "
            if response.status_code == http.HTTPStatus.SERVICE_UNAVAILABLE
            else f"NAMED ENTITY RECOGNITION FAILED [{response.status_code}]: "
            )
        raise Exception(error_type + response.text)
    result = response.json()["result"]
    return result

def process(config, infile, outfile, url, verbose=False):
    nodblb = config.no_double_lb or config.input_format != 'untokenized' or config.vertical_append
    output = outfile.open('w', encoding='utf-8') if outfile else sys.stdout
    buffer = []

    def analyze(buffer):
        analyze.counter += 1
        text = "\n".join([l.split('\t', 1)[0] for l in buffer]) if config.vertical_append or config.input_format=='vertical' else \
            "".join(buffer) if nodblb else "\n".join(buffer)+"\n"
        if verbose:
            sys.stderr.write(f"[{analyze.counter}] Sending {len(buffer)} lines to NameTag. ")
            sys.stderr.flush()
        result = nametag_lindat(
            model= config.model,
            text= text,
            informat= config.input_format if not config.vertical_append else 'vertical',
            outformat= config.output_format if not config.vertical_append else 'vertical',
            url=url
        )
        if not config.vertical_append:
            print(result, file=output)
        else:
            ne_map = {}
            for idx, ne_line in enumerate(result.split("\n")):
                if not ne_line.strip():
                    continue
                (linenums, netype, _) = ne_line.split('\t', 2)
                for linenum in linenums.split(','):
                    linenum = int(linenum)
                    if linenum not in ne_map:
                        ne_map[linenum] = []
                    ne_map[linenum].append(f"{netype}_{idx+1}")
            for i, line in enumerate(buffer):
                line = line.rstrip('\n\r')
                ne_str = "NE="+"-".join(ne_map[i+1]) if i+1 in ne_map else ''
                if not line:
                    if ne_str:
                        sys.stderr.write(f"ERROR: Named entity assigned to an empty line! Ignoring.\n")
                        sys.stderr.flush()
                    print(line, file=output)
                else:
                    print(line+'\t'+ne_str, file=output)
        if verbose:
            sys.stderr.write(f"Analyzed.\n")

    analyze.counter = 0

    with infile.open() if infile else sys.stdin as input_file:
        cnt = 0
        informat = config.input_format
        lastempty = False
        for line in input_file:
            # eliminate multiple empty lines, it makes NameTag linecounting broken for vertical input
            # (also empty line at the start of a vertical batch)
            if lastempty and not line.strip():
                continue
            lastempty = not line.strip()
            if not line.strip() or (informat=='untokenized' and not config.vertical_append):
                cnt += 1
            buffer.append(line)
            if cnt >= int(config.tagger_batch):
                analyze(buffer)
                buffer.clear()
                cnt = 0
        analyze(buffer)

    output.close()


if __name__ == '__main__':
    import argparse
    from pathlib import Path

    parser = argparse.ArgumentParser(description="Analyze text with NameTag (https://lindat.mff.cuni.cz/services/nametag/api-reference.php)")
    parser.add_argument("-m", "--model", help="UD language model to use", type=str, default=DEFAULT_MODEL)
    parser.add_argument("-i", "-f", "--infile", help="input file (default=STDIN)", type=str)
    parser.add_argument("-o", "--outfile", help="output file (default=STDOUT)", type=str)
    parser.add_argument("-u", "--url", help="NameTag API URL (default=LINDAT API)", type=str, default=NAMETAG_API_URL)
    parser.add_argument("-if", "--input-format", help="input format (untokenized/vertical/conllu)", type=str, default="untokenized")
    parser.add_argument("-of", "--output-format", help="output format (xml/vertical/conll/conllu-ne)", type=str, default="conllu-ne")
    parser.add_argument("-b", "--batch", help="batch size in lines (default=1000)", type=int, default="1000", dest="tagger_batch")
    parser.add_argument("-va", "--vertical-append", help="append to the vertical input as a new column (overrides input and output format)", action="store_true")
    parser.add_argument("-v", "--verbose", help="report progress", action="store_true")
    parser.add_argument("-nd", "--no-double-lb", help="do NOT double line breaks in untokenized input (a sequence of two linebreaks enforces a paragraph break)", action="store_true")
    args = parser.parse_args()
    
    infile = Path(args.infile) if args.infile else None
    outfile = Path(args.outfile) if args.outfile else None

    process(args, infile, outfile, args.url, args.verbose)