#!/usr/bin/env python3

# Copyright (c) 2023 Václav Horký <Vaclav.Horky@ff.cuni.cz>
# Copyright (c) 2024-2025 Pavel Vondřička <pavel.vondricka@ff.cuni.cz>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# dated June, 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import http
import requests
from pathlib import Path

# LINDAT service
UDPIPE_API_URL = "http://lindat.mff.cuni.cz/services/udpipe/api/process"
NAMETAG_API_URL = "http://lindat.mff.cuni.cz/services/nametag/api/recognize"
DEFAULT_MODEL = 'en'

def udpipe_lindat(model, text, ner=None, tokenizer="", tagger="", parser="", input=None, output=None, udpipe_url=UDPIPE_API_URL, nametag_url=NAMETAG_API_URL):
    """
    Send a text to UDPipe2 web service and return the result
    
    text : str
        text to analyze
    model : str
        language model to apply
    ner : NameTag named entity recognition model to apply (None=do not use NER)
    tokenizer : str | None
        tokenize as plain text?
    tagger : str | None
        perform analysis (lemmatization and tagging)?
    parser : str | None
        perform dependency parsing?
    input : str | None
        if the tokenizer is not used, the input is assumed to be in the specified input format
    output : str | None
        The output format (eventually with options) to use

    See also:
     * <http://lindat.mff.cuni.cz/services/udpipe/api-reference.php>
     * <https://universaldependencies.org/format.html>
     
    """
    
    params = {
        "model": model,
        "data": text
    }
    if tokenizer is not None:
        params["tokenizer"] = tokenizer
    if tagger is not None:
        params["tagger"] = tagger
    if parser is not None:
        params["parser"] = parser
    if input is not None:
        params["input"] = input
    if output is not None:
        params["output"] = output
    response = requests.post(udpipe_url, params)
    if not response.ok:
        error_type = (
            "TAGGER NOT AVAILABLE: "
            if response.status_code == http.HTTPStatus.SERVICE_UNAVAILABLE
            else f"TAGGING FAILED [{response.status_code}]: "
            )
        raise Exception(error_type + response.text)
    result = response.json()["result"]
    if ner:
        # Apply NameTag Named Entity Recognition
        params = {
            "model": ner if ner != 'auto' else model,
            "data": result,
            "input": "conllu",
            "output": "conllu-ne"
        }
        response = requests.post(nametag_url, params)
        if not response.ok:
            error_type = (
                "NAMETAG NOT AVAILABLE: "
                if response.status_code == http.HTTPStatus.SERVICE_UNAVAILABLE
                else f"NAMED ENTITY RECOGNITION FAILED [{response.status_code}]: "
                )
            raise Exception(error_type + response.text)
        result = response.json()["result"]
    return result

def process(config, infile, outfile, verbose=False):
    informat = config.get('tagger_input', 'plaintext')
    pretokenized = informat != 'plaintext'
    nodblb = config.getboolean('no_double_lb') or pretokenized
    output = outfile.open('w', encoding='utf-8') if outfile else sys.stdout
    buffer = []

    def analyze(buffer):
        analyze.counter += 1
        if verbose:
            sys.stderr.write(f"[{analyze.counter}] Sending {len(buffer)} lines to UD-pipe. ")
            sys.stderr.flush()
        print(udpipe_lindat(
            model= config.get('model', DEFAULT_MODEL),
            ner = config.get('named_entities'),
            # UD Pipe needs double "\n\n" to enforce paragraph breaks!
            text= "".join(buffer) if nodblb else "\n".join(buffer)+"\n",
            tokenizer= None if pretokenized else config.get('tokenizer_options', ''),
            tagger= None if config.getboolean('no_analysis') else config.get('tagger_options', ''),
            parser= None if config.getboolean('no_parsing') or config.getboolean('no_analysis') else config.get('parser_options', ''),
            input= None if config.get('tagger_input', 'plaintext')=='plaintext' else config.get('tagger_input'),
            output= config.get('tagger_output'),
            udpipe_url= config.get('udpipe_url'),
            nametag_url= config.get('nametag_url'),
            ),
            file = output)
        if verbose:
            sys.stderr.write(f"Analyzed.\n")

    analyze.counter = 0

    with infile.open() if infile else sys.stdin as input_file:
        vertical = informat.startswith('vertical') or informat.startswith('conllu')
        cnt = 0
        informat = config.get('tagger_input', 'plaintext')
        for line in input_file:
            if cnt >= config.getint('tagger_batch', 1000):
                analyze(buffer)
                buffer.clear()
                cnt = 0
            # count only empty lines (sentences) for vertical input, every line for other formats
            if not line.strip() or not vertical:
                cnt += 1
            buffer.append(line)
        if len(buffer):
           analyze(buffer)

    output.close()


if __name__ == '__main__':
    """
    Analyze text with UDPipe 2 (using LINDAT REST API: http://lindat.mff.cuni.cz/services/udpipe/api-reference.php)
    
    Input: STDIN by default
    
    Output: STDOUT
    
    Options: '-m <model>' Use the specified language model.
             (See http://ufal.mff.cuni.cz/udpipe/2/models for a list of currently available models)

             '-ner [<model>]' Apply NameTag Named Entity Recognition using the optionally specified model.
             By default, the value 'auto' means that the language model of the tagger is used.
             (See https://lindat.mff.cuni.cz/services/nametag/api/models for a list of currently available models)
             
             '-i <filename>' Read input from file instead of STDIN.

             '-o <filename>' Write output to file instead of STDOUT.

             '-if <format>' Input format.

             '-of <format>' Output format.

             '-b <number>' Specify batch size, i.e. number of lines to be send to the API at once.
             The REST API has a limit for maximal request size, probably around 1.3MB.
             Default: 1000

             '-na' Do not perform any analysis, just segmentation and tokenization.

             '-np' Do not perform syntactic parsing.

             '-nd' Do not double line breaks (as required for UDPipe to enforce paragraph breaks)

             '--tokenizer' Additional options for the tokenizer.

             '--tagger' Additional options for the tagger (analysis).

             '--parser' Additional options for the parser.
             
             '-v' Report progress to STDERR.
    
    """
    import sys
    import os
    import argparse
    import configparser

    parser = argparse.ArgumentParser(description="Analyze text with UD-pipe (http://lindat.mff.cuni.cz/services/udpipe/api-reference.php)")
    parser.add_argument("-c", "--config", help="additional config file", type=str)
    parser.add_argument("-p", "--profile", help="config profile to use", type=str, default='DEFAULT')
    parser.add_argument("-m", "--model", help="UD language model to use", type=str)
    parser.add_argument("-ner", "--named-entities", help="apply NameTag NER with the specified (optional) model", type=str, nargs='?', const='auto')
    parser.add_argument("--nametag-url", help="specify NameTag API URL (default: public LINDAT API)", type=str, default=NAMETAG_API_URL)
    parser.add_argument("--udpipe-url", help="specify UDpipe API URL (default: public LINDAT API)", type=str, default=UDPIPE_API_URL)
    parser.add_argument("-i", "-f", "--infile", help="input file (default=STDIN)", type=str)
    parser.add_argument("-o", "--outfile", help="output file (default=STDOUT)", type=str)
    parser.add_argument("-if", "--input-format", help="input format (if pre-tokenized; by default just plaintext to be tokenized internally)", type=str, default="plaintext", dest="tagger_input")
    parser.add_argument("-of", "--output-format", help="output format (default: connlu v2)", type=str, dest="tagger_output")
    parser.add_argument("-b", "--batch", help="batch size in lines (default=1000)", type=int, dest="tagger_batch")
    parser.add_argument("-na", "--no-analysis", help="do NOT perform any analysis (lemmatization, tagging or parsing); perform just segmentation and tokenization", action="store_true")
    parser.add_argument("-np", "--no-parsing", help="do NOT perform dependency parsing (syntax)", action="store_true")
    parser.add_argument("-nd", "--no-double-lb", help="do NOT double line breaks (UDPipe requires a sequence of two as paragraph break)", action="store_true")
    parser.add_argument("--tokenizer", help="additional options for the tokenizer", type=str, dest="tokenizer_options")
    parser.add_argument("--tagger", help="additional options for the tagger (ignored if --no-analysis is used)", type=str, dest="tagger_options")
    parser.add_argument("--parser", help="additional options for the syntactic parser (ignored if --no-analysis or --no-parsing is used)", type=str, dest="parser_options")
    parser.add_argument("-v", "--verbose", help="report progress", action="store_true")
    args = parser.parse_args()

    # read configuration from files
    scriptpath = path = os.path.dirname(os.path.realpath(__file__))
    curpath = os.getcwd()
    profiles = configparser.ConfigParser()
    profiles.read([scriptpath+'/xmlanntools.ini', curpath+'/xmlanntools.ini'])
    if args.config:
        read = profiles.read(args.config)
        if read != [args.config]:
            raise Exception("Failed reading configuration file: '{0}'".format(args.config))

    # if no profile was specified, check whether the DEFAULT profile specifies a default profile
    cur_profile = args.profile
    if cur_profile == 'DEFAULT' and profiles[cur_profile].get('profile'):
        cur_profile = profiles[cur_profile].get('profile')

    # evt. update/override currently selected profile configuration with values from command-line arguments
    profiles.read_dict({cur_profile: {k: v for k, v in vars(args).items() if v is not None and v != False}})
    config = profiles[cur_profile]

    infile = Path(args.infile) if args.infile else None
    outfile = Path(args.outfile) if args.outfile else None

    process(config, infile, outfile, args.verbose)
