[DEFAULT]
profile = tei_default

[tei_default]
### xml2standoff ###
text_elements = head p
exclude_elements = teiHeader foreign del
#keep_linebreaks = no

### tag_ud ###
model = en
named_entities = auto

### ann2standoff ###
preprocess = conllu
attributes = n synword lemma upos xpos feats head deprel deps _
virtual_tokens = dtok
punctuation = upos=PUNCT
#virtual_token_attr = form
#token_element = w
#punct_element = pc
#sentence_element = s
#ne_element = ne
#ne_type_attr = type

### standoff2xml ###
warn_breaking_except = hi emph i b u
#keep_between_sentences = no
nest_elements = del
#tokens_only = no
#merge_elements = w

[conllu]
preprocess = conllu
attributes = n synword lemma upos xpos feats head deprel deps misc
multi_separator = |
multi_separator_feats = ||

[cnk_ud]
preprocess = conllu
multi_separator = |
multi_separator_feats = ||
attributes = n synword lemma upos xpos feats head deprel deps _

[syn2020]
attributes = sforma lemma sublemma tag verbtag afun parent eparent prep p_tag p_lemma p_afun ep_tag ep_lemma ep_afun

[cnk2020]
attributes = sforma lemma sublemma tag verbtag

[cnk2020lemur]
attributes = sword lemma sublemma tag verbtag col_lemma col_type
